site_name: My MkLorum
# repo_url: https://github.com/example/repository/
site_description: This a Demo
pages:
   - Home: index.md
   - About: about.md
   - 'Overview.md'
   - 'Concepts.md' 
   - How Tos: HowTos.md
   - Cloud Foundry: cloudFoundry.md
   - Test: 
      - Page 1: test/page1.md
      - Page 2: test/page2.md
# theme: mkdocs
# theme: readthedocs

# third Party theme
# theme: Cinder

# theme:
#   name: 'material'
#   custom_dir: 'theme'
#   palette:
#     primary: 'teal'
#     accent: 'teal'
#   language: 'en'
#   favicon: 'img/favicon.ico'
#   feature:
#     tabs: true


extra_css: [css/extra.css]
extra_javascript: [js/extra.js]
dev_addr: 127.0.0.1:5000